default_timezone = "America/New_York"

[extensions.opcache]
enabled=true
zend=true

[extensions.opcache.config]
validate_timestamps = true

[extensions.xdebug]
enabled=false
zend=true

[extensions.xdebug.config]
remote_enable=1
remote_autostart=1
remote_port=9000
remote_connect_back=1

[extensions.apc.config]
enabled = true
shm_size = "128M"
shm_segments = 1
ttl = 7200
enable_cli = true

[pm]
type = "dynamic"
max_children = 50
start_servers = 5
min_spare_servers = 1
max_spare_servers = 10

[error]
reporting = "E_ALL & ~E_NOTICE"
display = false

[limit]
memory = "200M"
post = "200M"

[cache]
size = "512M"

[path]
ping = "/.well-known/php-fpm/ping"
status = "/.well-known/php-fpm/status"

[network]
port = 9123

[access]
log = false
format = ""

[sendmail]
path = "-t -i"
