#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

# test that php-fpm responds on path.ping

{{#if cfg.path.ping}}
    {{ pkg.svc_config_path }}/fpm-exec GET "{{ cfg.path.ping }}" | grep pong
{{/if}}

