#!/bin/bash -e

mkdir -p "{{ pkg.env.PHP_EXTENSION_DIR }}" || {
    echo "Unable to create PHP_EXTENSION_DIR, skipping extension linking: {{ pkg.env.PHP_EXTENSION_DIR }}"
    exit 0
}

for php_extension_source in ${PHP_EXTENSION_SOURCES//:/ }; do
    if [ -d "${php_extension_source}" ]; then
        ln -sfv "${php_extension_source}"/* "{{ pkg.env.PHP_EXTENSION_DIR }}/"
    fi
done
