#!/bin/bash

exec 2>&1

set -a
. "{{pkg.svc_config_path}}/env"
set +a

exec {{ pkg.env.PHP_FPM }} \
    --nodaemonize \
    --fpm-config {{pkg.svc_config_path}}/php-fpm.conf \
    -c {{pkg.svc_path}}/config_install/php.ini
