#!{{pkgPathFor "core/bash"}}/bin/bash -e

exec 2>&1

# re-run install script
{{pkg.svc_path}}/hooks/install

set -a
. "{{pkg.svc_config_path}}/env"
set +a

exec {{ pkg.env.PHP_FPM }} \
    --nodaemonize \
    --fpm-config "{{pkg.svc_config_path}}/php-fpm.conf" \
    -c "{{pkg.svc_config_path}}/php.ini"
