#!/bin/bash -e

pkg_extensions_dir="{{ pkg.path }}/extensions-{{ pkg.env.PHP_ZEND_API_VERSION }}"
if [ -d "{{ pkg.env.PHP_EXTENSION_DIR }}" ] && [ -d "${pkg_extensions_dir}" ]; then
    ln -sfv "${pkg_extensions_dir}"/* "{{ pkg.env.PHP_EXTENSION_DIR }}/"
fi
