 #    #   ####      #    #    #  #    #
 ##   #  #    #     #    ##   #   #  #
 # #  #  #          #    # #  #    ##
 #  # #  #  ###     #    #  # #    ##
 #   ##  #    #     #    #   ##   #  #
 #    #   ####      #    #    #  #    #
 # For help with NGINX Config Tuning,
 # refer to: http://nginx.org/en/docs/http/ngx_http_core_module.html



#### General Configuration
# redirector: If set, bypass normal config and just redirect http to https
# redirector = true
# worker_processes: Number of NGINX processes. Default = 1
worker_processes = "auto"
worker_rlimit_nofile = 8192



#### Events Context Configuration
[events]
# worker_connections: Connections per Worker Process.  Default = 1024
worker_connections = 1024


#### HTTP Context Configuration
[http]
# http.sendfile: Enable (on) or disable (off) Sendfile Support.  Default = on
sendfile = "on"

# http.tcp_nopush: Enable (on) or disable (off) use of TCP_NOPUSH or TCP_CORK socket option. Default = on
tcp_nopush = "on"

# http.tcp_nodelay: Enable (on) or disable (off) use of the TCP_NODELAY option. Default = on
tcp_nodelay = "on"

# http.keepalive_timeout: Timeout on client connection keepalive, in seconds. Default = 75
keepalive_timeout = 60

# http.client_header_timeout: Defines a timeout for reading client request header. Default = 60s
client_header_timeout = "10m"

# http.client_body_timeout: Defines a timeout for reading client request body. Default = 60s
client_body_timeout = "10m"

# http.client_max_body_size: Sets the maximum allowed size of the client request body, specified in the “Content-Length” request header field. Default = 1m
client_max_body_size = "200m"

# http.send_timeout: Sets a timeout for transmitting a response to the client. Default = 60s
send_timeout = "10m"

# http.fastcgi_read_timeout: Defines a timeout for reading a response from the FastCGI server. Default = 6h
fastcgi_read_timeout = "6h"

# http.fastcgi_buffer_size: Sets the size of the buffer used for reading the first part of the response received from the FastCGI server. Default = 32k
fastcgi_buffer_size = "32k"

# http.fastcgi_buffers: Sets the number and size of the buffers used for reading a response from the FastCGI server, for a single connection. Default = 16 16k
fastcgi_buffers = "16 16k"

# http.fastcgi_keep_conn: When this directive is set to the value on, nginx will instruct a FastCGI server to keep connections open. Default = on
fastcgi_keep_conn = "on"

# http.fastcgi_index: Sets a file name that will be appended after a URI that ends with a slash, in the value of the $fastcgi_script_name variable. Default = index.php
fastcgi_index = "index.php"

# optional access log
access_log = ""

[http.listen]
port = 80

[upstream]
keepalive = 32

[default_server]
root = false # defaults to {{pkg.path}}/www
index = "index.html"
