 #    #   ####      #    #    #  #    #
 ##   #  #    #     #    ##   #   #  #
 # #  #  #          #    # #  #    ##
 #  # #  #  ###     #    #  # #    ##
 #   ##  #    #     #    #   ##   #  #
 #    #   ####      #    #    #  #    #
 # For help with NGINX Config Tuning,
 # refer to: http://nginx.org/en/docs/http/ngx_http_core_module.html



#### General Configuration
# redirector: If set, bypass normal config and just redirect http to https
# redirector = true
# worker_processes: Number of NGINX processes. Default = 1
worker_processes = "auto"
worker_rlimit_nofile = 8192



#### Events Context Configuration
[events]
# worker_connections: Connections per Worker Process.  Default = 1024
worker_connections = 1024


#### HTTP Context Configuration
[http]
# http.sendfile: Enable (on) or disable (off) Sendfile Support.  Default = on
sendfile = "on"

# http.tcp_nopush: Enable (on) or disable (off) use of TCP_NOPUSH or TCP_CORK socket option. Default = on
tcp_nopush = "on"

# http.tcp_nodelay: Enable (on) or disable (off) use of the TCP_NODELAY option. Default = on
tcp_nodelay = "on"

# http.keepalive_timeout: Timeout on client connection keepalive, in seconds. Default = 75
keepalive_timeout = 60

# http.client_header_timeout: Defines a timeout for reading client request header. Default = 60s
client_header_timeout = "10m"

# http.client_body_timeout: Defines a timeout for reading client request body. Default = 60s
client_body_timeout = "10m"

# http.client_max_body_size: Sets the maximum allowed size of the client request body, specified in the “Content-Length” request header field. Default = 1m
client_max_body_size = "200m"

# http.send_timeout: Sets a timeout for transmitting a response to the client. Default = 60s
send_timeout = "10m"

# http.fastcgi_read_timeout: Defines a timeout for reading a response from the FastCGI server. Default = 6h
fastcgi_read_timeout = "6h"

# optional access log
access_log = ""

[http.listen]
port = 80

[server]
root = ""
index = "index.html"
