#!/bin/bash -e

{{# if cfg.default_server.stub_status_path}}
# test stub_status response
curl -s http://{{ sys.ip }}:{{ cfg.http.listen.port }}{{cfg.default_server.stub_status_path}} | grep "Active connections:"
{{/if}}
