#!/bin/bash -e

mkdir -p "/hab/svc/php/var/extensions-{{ pkg.env.PHP_API_VERSION }}/"
ln -sf "{{pkg.path}}/lib/php/extensions/no-debug-non-zts-{{ pkg.env.PHP_API_VERSION }}"/* "/hab/svc/php/var/extensions-{{ pkg.env.PHP_API_VERSION }}/"
